# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Qizan Chen"
description:	       "Molecular Simulation Gallary| Ready to Work/Intern"
author:              "Qizan Chen"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
